spring:
  application:
    name: login-users-employees
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        jdbc:
          time_zone: America/Sao_Paulo
server:
  port: ${PORT:8082}
  address: 0.0.0.0
